### ISSUE TITLE
Finalize-HRTF-Simulation Issue

### ISSUE THREAD

**Issue by saragh21** [Any2HRTF/Mesh2HRTF#142]
Hello! Thank you for the documents! I work with mesh2hrtf tools for good-quality head and ear scans at Aalto Acoustics lab. When I checked my results from NumCalc simulation it indicated 'All NumCal projects finished' and NC.out files seem to be correct, after running Finalize-HRTF-Simulation.py it immediately crashed and said "Most likely some or all simulation steps failed" do you have any idea which steps might be wrong?
 
![photo_2024-09-06_14-54-40](https://github.com/user-attachments/assets/1df68940-caa9-4b8e-add8-bc4bd4f86f92)
![photo_2024-09-06_14-54-36](https://github.com/user-attachments/assets/90685444-4ef6-4260-86b9-0a6747066e98)

In addition, I have one question related to the sculpting or smoothing part can I modify meshes after the hrtf mesh grading step on the left and right sides separately? and export files blender them, or if it may cause some issues on my simulation?

**Comment by f-brinkmann** [comment]
Hi, Finalize-HRTF-Simulation.py is part of https://sourceforge.net/p/mesh2hrtf-tools/code/ci/master/tree/ and not officially supported by us, because it is a very specific work-flow. Please post your question there or directly use the mesh2hrtf api.

What might have happened, is that some files did not get copied if you ran the simulations on a different machine. I always zip before I copy.

Sculpting after grading is generally not a problem. I assume you want to scult sharp edges at the contralateral ear?

I'll be in alto for a week starting next Wednesday, if you want we can meet to check the error and catch up...

**Comment by saragh21** [comment]
Thank you very much for your response! I suspect the issue might indeed be related to an earplug of one side I attempted to adjust with draw tools similar to tutorials prior to mesh grading, and I am currently working on optimizing that aspect.

It would be a great opportunity to meet and discuss the error in detail, and I look forward to catching up with you in Aalto next week. Please let me know a convenient time for you.

**Comment by f-brinkmann** [comment]
Not sure yet, what time will be good. Let's connect once I'm there...

**Comment by f-brinkmann** [comment]
This was resolved offline and seemed to be an error in handling mesh2hrtf-tools or in using mesh2hrtf-tools. Directly using the official Mesh2HRTF Python API worked out of the box.
