### ISSUE TITLE
Bug in Matlab/Octave API

### ISSUE THREAD

**Issue by f-brinkmann** [Any2HRTF/Mesh2HRTF#4]
In the develop branch `Output2HRTF_ReadComputationTime.m` raises an error, when trying to parse the attached file:

```
Index in position 1 is invalid. Array indices must be positive integers or logical values.

Error in Output2HRTF_ReadComputationTime (line 71)
        data(count,7) = sscanf(line(idx2+1:end-1), '%f');

Error in Output2HRTF_Main (line 128)
        tmp=Output2HRTF_ReadComputationTime(['NumCalc', filesep, 'source_', ...

Error in Output2HRTF (line 27)
[NC.zip](https://github.com/Any2HRTF/Mesh2HRTF/files/8618102/NC.zip)

Output2HRTF_Main(Mesh2HRTF_version, ...
```

The file is read correctly by the Python API

@germknoedlspeck can you take a look?

[NC.zip](https://github.com/Any2HRTF/Mesh2HRTF/files/8618103/NC.zip)

**Comment by f-brinkmann** [comment]
yes - of course. For some reason I could not upload it. Here is the text directly...

#####################################
######## General information ########
#####################################

Program: Mesh2HRTF 1.0.0
Title: Head-Related Transfer Functions
Source type: Left ear
Evaluation Grids:
    C:\some\path\Mesh2HRTF\mesh2hrtf\Mesh2Input\EvaluationGrids\Default

#####################################
####### Frequency information #######
#####################################

Minimum evaluated Frequency: 172.265625
Highest evaluated Frequency: 22050.000000
Frequency Stepsize: 172.265625
Frequency Steps: 128

**Comment by germknoedlspeck** [comment]
Hi - again, I need to request additional files 😬 
When I try to reproduce the issue now, this is the error I get:

Error using Output2HRTF_Main (line 159)
This case is not yet implemented.

This is due to the lack of the folder structure NumCalc/source_1 or /source_2, which the code is looking for. Before I start creating folders that may look different in your setup, could you please attach all the folders necessary as well? Basically, the whole folder "NumCalc" of the project. Thank you 😄 Apologies for the inconvenience!
