### ISSUE TITLE
Add calculation of diffuse field compensated HRTFs / HRIRs

### ISSUE THREAD

**Issue by f-brinkmann** [Any2HRTF/Mesh2HRTF#44]
Do we want to add an option 'Compute DIR' (Directional Impulse Responses) to the Blender Export?

It would be easy to add for the Python part, since pyfar already has a function for estimating Voronoi weights for averaging HRTFs from arbitrary grids. If that is available also in Matlab, it would be simple to compute using using hrtf2dtf from the SOFAtoolbox. And it would be and helpful in many cases.

@petibub, @germknoedlspeck - what do you think? I also wonder if we should apply any fractional octave smoothing by default (probably not)

**Comment by petibub** [comment]
This might be useful indeed, however, I'd call it "Compute DTFs (diffuse-field equalized HRTFs)" because the time-domain equivalent "DIR" is not used in that context and might be confused with directional room impulse responses (DRIRs). 

I think that we should avoid any type of spectral processing per default. But of course, we can add that as an option, as long as it is clearly formulated...

**Comment by f-brinkmann** [comment]
`compute_dtfs` for the function name and optional smoothing sounds good to me. @germknoedlspeck would you implement that for Matlab? If yes, I will prepare the mesh2input Blender export and implement it in Python.

**Comment by germknoedlspeck** [comment]
Within the SOFAtoolbox, there is a function called SOFAhrtf2dtf, which can be called with the desired HRIR SOFA object. It's not a problem for me to implement, I'm just asking whether we need this functionality in Mesh2HRTF as well as in the SOFAtoolbox?

**Comment by f-brinkmann** [comment]
I think it might be useful for less experienced users who could use the DTFs for auralizations instead of applying a headphone compensation.
