### ISSUE TITLE
Add resampling for HRTFs / HRIRs

### ISSUE THREAD

**Issue by f-brinkmann** [Any2HRTF/Mesh2HRTF#47]
The upcoming pyfar release will contain a resampling function. This will make it easy to add resampling to the Mesh2HRTF API. The release is scheduled for October.

@SDX-LV - might be intersting for you.

**Comment by germknoedlspeck** [comment]
@petibub Does this fit in the Mesh2HRTF environment or would it be better if @f-brinkmann submit this functionality to the SOFAtoolbox?

**Comment by f-brinkmann** [comment]
Can't commit to SOFAtoolbox unfortunately because it's Python. If you want something like this for SOFA, I can give you Matlab Code I have lying around, though :)

As with the DTF, this would be a good feature for less experienced users. And since it is still related to outputting the HRTF / HRIRs in a useable format, I thought it might fit here.

**Comment by SDX-LV** [comment]
I need to look into this, but so far I was good with getting both 48 and 44.1 kHz from a single simulation. 
It may be interesting for some cases to up sample to 96kHz - for people with diamond ears. Because it is hard to simulate so high frequencies.

It may be enough to add a brief tutorial or a script here or on "Mesh2HRTF_tools" about the resampling process and how to use it.

**Comment by petibub** [comment]
In Matlab/Octave, the resampling is just resample(), isn't? But we could create SOFAresample(.), if this would help...

**Comment by f-brinkmann** [comment]
Yes I think `resample` could be used but would require a convenient parameter handling similar to pyfar resample: https://pyfar.readthedocs.io/en/develop/_modules/pyfar/dsp/interpolation.html#resample

**Comment by petibub** [comment]
I opened an issue in the SOFA toolbox to add SOFAresample as an extension...
