### ISSUE TITLE
manage_numcalc_script.py FileNotFoundError

### ISSUE THREAD

**Issue by terrainer** [Any2HRTF/Mesh2HRTF#51]
Hi, getting an issue when trying to run manage_numcalc_script.py using Anaconda.
Honestly not sure what the issue is, I've followed all the instructions.

(mesh2hrtf) E:\>python "E:\Mesh2HRTF\mesh2hrtf-tools-code-8b8a0d23381280b463c95115e1aff9ad6f05d642\manage_numcalc_script.py"
←[0m
Starting manage_numcalc with the following arguments [Sep 04 2022, 21:34:44]
----------------------------------------------------------------------------
project_path: E:\Mesh2HRTF\mesh2hrtf-tools-code-8b8a0d23381280b463c95115e1aff9ad6f05d642
numcalc_path: Searching NumCalc.exe
max_ram_load: 31.854000091552734
ram_safety_factor: 1.05
max_cpu_load: 90
max_instances: 16
wait_time: 15
starting_order: alternate
confirm_errors: True

←[0mNumCalc executable: E:\Mesh2HRTF\mesh2hrtf-tools-code-8b8a0d23381280b463c95115e1aff9ad6f05d642\NumCalc_WindowsExe\NumCalc.exe

←[0mObtaining RAM estimates for E:\Mesh2HRTF\mesh2hrtf-tools-code-8b8a0d23381280b463c95115e1aff9ad6f05d642\myHRTF_project_L\NumCalc\source_1
Traceback (most recent call last):
  File "E:\Mesh2HRTF\mesh2hrtf-tools-code-8b8a0d23381280b463c95115e1aff9ad6f05d642\manage_numcalc_script.py", line 104, in <module>
    m2h.manage_numcalc(
  File "e:\mesh2hrtf\mesh2hrtf\NumCalc\manage_numcalc.py", line 230, in manage_numcalc
    all_instances, instances_to_run, *_ = _check_project(
  File "e:\mesh2hrtf\mesh2hrtf\NumCalc\manage_numcalc.py", line 499, in _check_project
    subprocess.run(
  File "C:\Users\Terra\anaconda3\envs\mesh2hrtf\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Terra\anaconda3\envs\mesh2hrtf\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Terra\anaconda3\envs\mesh2hrtf\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by SDX-LV** [comment]
Hi, 
You were a bit unlucky that the tutorial is already updated, but the code does is not include the recent Windows compatibility fixes. 

I am 99% sure that if you substitute `manage_numcalc.py` and `manage_numcalc_script.py` in "e:\mesh2hrtf\mesh2hrtf\NumCalc" with files from here: https://github.com/SDX-LV/Mesh2HRTF_contributions/tree/manage_numcalc_fixes/mesh2hrtf/NumCalc  then it should work.

Otherwise you can wait for a new commit to these files in the main repository. (note these are just manager scripts - the actual NumCalc solver that affects the results is the same and stable).

**Comment by terrainer** [comment]
I ended up using the version you suggested on [this issue](https://github.com/Any2HRTF/Mesh2HRTF/issues/48) and it looks like it's going well.
