### ISSUE TITLE
How to use hrtf_mesh_grading in a 1.x workflow?

### ISSUE THREAD

**Issue by marclava** [Any2HRTF/Mesh2HRTF#61]
Hi Mesh2HRTF team,

I tried to follow the beginner's tutorial, but I'm a Linux user... 
Then I found there's a new version in the making ('develop' branch) with a corresponding documentation: https://github.com/Any2HRTF/Mesh2HRTF/wiki/Mesh2HRTF-1.x
I was able to follow the hrtf tutorial: https://github.com/Any2HRTF/Mesh2HRTF/wiki/Unix_Tutorials#hrtf-tutorial
But  I don't understand how to use the hrtf_mesh_grading software; it can be used to create 2 optimized models, one for each ear, but how to use them in 1.x workflow?

Thanks for your attention and help.

**Comment by marclava** [comment]
> If you leave an e-mail, I can send you the current version.

I sent you an email.

**Comment by SDX-LV** [comment]
Hi, 
Even if you use Linux, most of the steps, settings and explanations are exactly the same: https://github.com/Any2HRTF/Mesh2HRTF/wiki/Basic_3D_optimization_and_ReMeshing#get-the-hrtf_mesh_grading

In the tutorial there is also a link to the original GitHub repository with usage instructions for Linux. In the end you can use the beginner's tutorial (video or text) and instead of running .bat files for Windows, execute about the same commands in Linux terminal (you can even look inside .bat files to see what is executed).

**Comment by marclava** [comment]
Quick notification: I made it!

**Comment by marclava** [comment]
The issue is closed, but here's what I did that seemed to fix the issue: for each mesh (left and right), I assigned only one "ear" material, leaving the Skin material on the contralateral ear. Does it makes sense? I had the impression that the exported Mesh2HRTF projects were not excluding the contralateral ears from the simulations...

**Comment by f-brinkmann** [comment]
If both ears would be included, it would be a bug. Can you share the NC.inp files from the NumCalc/source_* folders for both cases? Then I could have a look.

**Comment by marclava** [comment]
I sent you an email with the NC.inp files.
