### ISSUE TITLE
Add check for duplicate nodes (in evaluation grids)

### ISSUE THREAD

**Issue by f-brinkmann** [Any2HRTF/Mesh2HRTF#80]
Mesh2HRTF defines nodes for the object meshes and evaluation grids and the nodes have to be unique. This is prone to errors and it would be easy to check if each node is unique upon export from Blender. See also #78

**Comment by SDX-LV** [comment]
I am thinking how to modify the https://sourceforge.net/p/mesh2hrtf-tools/code/ci/master/tree/extra_Evaluation_Grids/generate_mesh2hrtf_evaluation_grid.py script to handle this unique ID requirement. But it is quite tricky when there is no centralized node ID database (which is a bad idea).

I could make some arbitrary increments so that likelihood of overlapping IDs is greatly reduced, but the only robust solution I can think of is on the NumCalc side:

- Ideally when NumCalc loads each evaluation grid, it should re-number the node IDs to use numbers from for example 10^6 and up. Then there are 10^6 nodes reserved for the 3D mesh and all the evaluation grids will always get valid IDs which would be the same for left and right ear simulations.

**Comment by f-brinkmann** [comment]
I was thinking to check this upon Blender export which might be easier than changing NumCalc. I'll give it a shot in the next weeks

**Comment by petibub** [comment]
I suggest to put it on the to-do list for the next release. We really should release 1.0 as soon as possible because the corresponding paper will be published in any moment...

**Comment by f-brinkmann** [comment]
yes!

**Comment by f-brinkmann** [comment]
closed by #86
