### ISSUE TITLE
Save Blender Project as copy upon project export

### ISSUE THREAD

**Issue by f-brinkmann** [Any2HRTF/Mesh2HRTF#99]
Currently the blender project is saved in the project folder upon export. This might loose changes to the original file, if it is saved somewhere else.

**Comment by SDX-LV** [comment]
Hi,

If you are looking into better saving of Blender files, there are 2 more improvements to consider:

1. Save only the mesh that is being exported. Otherwise the .blend file can still be big and confusing if you have multiple high-rez iterations plus left and right side meshes in the same file. (this would also make it easier to use "save pictures" feature)
2. Save compressed .blend file (unless this is already added in current version?). Strange that this is still not a default option in Blender.
 
/Sergejs

**Comment by f-brinkmann** [comment]
Using compressed save would be a good option. Not sure if we should delete objects from the project since some people might have them in there for documentation purposes. If they are in the way of the rendered images, I assume they could be made invisible.

I currently don't have time to work on this - let's see if the good first issue tag lures in contributors. If someone wants to work on this, I'm happy to give hints on where to start.
